[package]
name = "mklink"
version = "1.0.0"
authors = ["Starz0r <starz0r@starz0r.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.21"
owo-colors = "1.2.0"
junction = "0.2.0"

[dev-dependencies]
winapi = { version = "0.3.9", features = ["std"] }